global:
  resolve_timeout: 1m

route:
  group_by: ['instance', 'severity', "warning"]
  # wait to send notification
  group_wait: 1s
  # wait to resend notification
  repeat_interval: 1h
  routes:
  - match:
      # alert name defined in alerting_rules.yml
      
      alertname: hourly income less than 0.5
  receiver: 'slack-hook'


receivers:
- name: 'slack-hook'
  slack_configs:
  - api_url: "https://hooks.slack.com/services/xx/yyy/zzzz"
    # title: "{{ .CommonAnnotations.summary }}"
    # title_link: ""
    # text: "Alerts for GC , GBC and Router"
    send_resolved: false
    text: |-
      {{ range .Alerts }}
        *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
        *Description:* {{ .Annotations.description }}
        *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
        *Details:*
        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}
    title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing
      | len }}{{ end }}] Monitoring Event Notification'

