global:
  scrape_interval:     60s
  evaluation_interval: 30s
  scrape_timeout: 30s

  # external_labels:
  #     monitor: 'exporter-metrics'

rule_files:
  - 'test-alert.test'
  - 'alert.rules.host'
  - 'alert.rules.prod'


alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]


scrape_configs:
  - job_name: 'pushgateway'
    honor_labels: true
    scrape_interval: 30s
    scrape_timeout: 15s
    tls_config:
      insecure_skip_verify: true
    static_configs:
    - targets: ['pushgateway:9091']
  - job_name: 'validator'
    honor_labels: true
    static_configs:
    - targets: ['validator:8081']
    scrape_interval: 30s
    scrape_timeout: 15s
    tls_config:
      insecure_skip_verify: true
  - job_name: 'beacon node'
    honor_labels: true
    static_configs:
      - targets: ['node:8080']
    scrape_interval: 30s
    scrape_timeout: 15s
    tls_config:
      insecure_skip_verify: true
  # - job_name: 'slasher'
  #   static_configs:
  #     - targets: ['localhost:8082']

  - job_name: 'production'
    scrape_interval: 30s
    scrape_timeout: 15s
    static_configs:
      - targets:
        - 'localhost:9090'
        labels:
          server: PRODUCTION
      - targets:
        - 'cadvisor:8080'
        labels:
          server: PRODUCTION
      - targets:
        - 'node-exporter:9100'
        labels:
          server: PRODUCTION
      - targets:
        - 'router:8081'
        labels:
          server: PRODUCTION

  # - job_name: 'node'
  #   honor_labels: true
  #   scrape_interval: 30s
  #   scrape_timeout: 15s
  #   # tls_config:
  #   #   insecure_skip_verify: true
  #   static_configs:
  #   - targets: ['localhost:9090']
  #     # labels:
  #     #     server: node
  #   - targets:
  #       - 'node-exporter:9100'
  #     # labels:
  #     #     server: node

  # - job_name: 'cadvisor'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['cadvisor:8080']

  # - job_name: 'prometheus'
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ['localhost:9090']

  - job_name: "node"
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090','node-exporter:9100']
