{
 "title": "Gnosis Beacon Chain Validators",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node_job", "query": "beacon node" },
   { "name": "validator_job", "query": "validator" },
   {
    "name": "fiat",
    "label": "Currency converter",
    "query": {
     "query": "label_values(crypto_currency, pair)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Validators statuses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(validator_statuses) or on() vector(0)",
     "legendFormat": "Total"
    },
    {
     "expr": "count(validator_statuses==3) or on() vector(0)",
     "legendFormat": "Active"
    },
    {
     "expr": "count(validator_statuses==2) or on() vector(0)",
     "legendFormat": "Pending"
    },
    {
     "expr": "count(validator_statuses==1) or on() vector(0)",
     "legendFormat": "Deposited"
    },
    {
     "expr": "count(validator_statuses==5) or on() vector(0)",
     "legendFormat": "Slashing"
    },
    {
     "expr": "count(validator_statuses==4) or on() vector(0)",
     "legendFormat": "Exiting"
    },
    {
     "expr": "count(validator_statuses==6) or on() vector(0)",
     "legendFormat": "Exited"
    },
    {
     "expr": "count(validator_statuses==0) or on() vector(0)",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Hourly earning",
   "type": "stat",
   "description": "This panel shows the earning during the last hour, and the annualized % of the hourly earning.\n\nThose data won't be shown until the first validator is at least one hour old, or that you started Prometheus at least one hour ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1h) - count(validator_balance > 16)*32 + count(validator_balance offset 1h > 0)*32)*absent(crypto_currency{pair=~\"mGNO$fiat\"})",
     "legendFormat": "mGNO"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1h) - count(validator_balance > 16)*32 + count(validator_balance offset 1h > 0)*32)*sum(crypto_currency{pair=\"mGNO$fiat\"})",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1h) - count(validator_balance > 16)*32 + count(validator_balance offset 1h > 0)*32)/(avg_over_time(count(validator_balance > 16)[1h:30s])*32/24/365)*100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Daily earning",
   "type": "stat",
   "description": "This panel shows the earning during the last day, and the annualized % of the daily earning.\n\nThose data won't be shown until the first validator is at least one day old, or that you started Prometheus at least one day ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1d) - count(validator_balance > 16)*32 + count(validator_balance offset 1d > 0)*32)*absent(crypto_currency{pair=~\"mGNO$fiat\"})/32",
     "legendFormat": "GNO"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1d) - count(validator_balance > 16)*32 + count(validator_balance offset 1d > 0)*32)*sum(crypto_currency{pair=\"mGNO$fiat\"})",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1d) - count(validator_balance > 16)*32 + count(validator_balance offset 1d > 0)*32)/(avg_over_time(count(validator_balance > 16)[1d:12m])*32/365)*100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Weekly earning",
   "type": "stat",
   "description": "This panel shows the earning during the last week, and the annualized % of the weekly earning.\n\nThose data won't be shown until the first validator is at least one week old, or that you started Prometheus at least one week ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1w) - count(validator_balance > 16)*32 + count(validator_balance offset 1w > 0)*32)*absent(crypto_currency{pair=~\"mGNO$fiat\"})/32",
     "legendFormat": "GNO"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1w) - count(validator_balance > 16)*32 + count(validator_balance offset 1w > 0)*32)*sum(crypto_currency{pair=\"mGNO$fiat\"})",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1w) - count(validator_balance > 16)*32 + count(validator_balance offset 1w > 0)*32)/(avg_over_time(count(validator_balance > 16)[1w:84m])*32*7/365)*100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Monthly earning",
   "type": "stat",
   "description": "This panel shows the earning during the last month, and the annualized % of the monthly earning.\n\nThose data won't be shown until the first validator is at least one month old, or that you started Prometheus at least one month ago. Ensure to run Prometheus with the flag `--storage.tsdb.retention.time=31d` if you want this panel to get enough data\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 30d) - count(validator_balance > 16)*32 + count(validator_balance offset 30d > 0)*32)*absent(crypto_currency{pair=~\"mGNO$fiat\"})/32",
     "legendFormat": "GNO"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 30d) - count(validator_balance > 16)*32 + count(validator_balance offset 30d > 0)*32)*sum(crypto_currency{pair=\"mGNO$fiat\"})",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 30d) - count(validator_balance > 16)*32 + count(validator_balance offset 30d > 0)*32)/(avg_over_time(count(validator_balance > 16)[30d:6h])*32/12)*100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Total earning",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance) - count(validator_balance > 16 and validator_statuses == 3)*32*absent(crypto_currency{pair=~\"mGNO$fiat\"}))/32",
     "legendFormat": "GNO"
    },
    {
     "expr": "(sum(validator_balance) - count(validator_balance > 16 and validator_statuses == 3)*32)*sum(crypto_currency{pair=\"mGNO$fiat\"})",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_balance) - count(validator_balance > 16 and validator_statuses == 3)*32)*100/(count(validator_balance > 16 and validator_statuses == 3)*32)",
     "legendFormat": "ROI"
    }
   ]
  },
  {
   "title": "Validator process started",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"$validator_job\"})/3600"
    }
   ]
  },
  {
   "title": "Total balance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(validator_balance > 16)/32", "legendFormat": "Total balance" }
   ]
  },
  {
   "title": "Validators total earnings",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "(validator_balance>16)-32" }
   ]
  },
  {
   "title": "VALIDATOR",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Validators daily income",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "((validator_balance > 16) - (validator_balance offset 1d > 16))",
     "legendFormat": "ss"
    }
   ]
  },
  {
   "title": "Validators hourly income",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "((validator_balance > 16) - (validator_balance offset 1h > 16))"
    }
   ]
  },
  {
   "title": "Validators hourly income - Average Joes",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "((validator_balance > 16) - (validator_balance offset 1h > 16))<0.0015"
    }
   ]
  },
  {
   "title": "Number of average joe validators (hourly)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "count(((validator_balance > 16) - (validator_balance offset 1h > 16))<0.0015)"
    }
   ]
  },
  {
   "title": "Validators hourly income - Winners",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "0<((validator_balance > 16) - (validator_balance offset 1h > 16))>=0.0015"
    }
   ]
  },
  {
   "title": "Number of winner validators (hourly)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "count(0.0015<((validator_balance > 16) - (validator_balance offset 1h > 16)))"
    }
   ]
  },
  {
   "title": "HARDWARE USAGE",
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "NODE" }
   ]
  },
  {
   "title": "NODE",
   "type": "stat",
   "gridPos": { "h": 1, "w": 11, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "NODE" }
   ]
  },
  {
   "title": "Warn: The process just restarted",
   "type": "graph",
   "description": "This alert is useful only for people who has automatic restart of the process after crash. \nThis can be made for example by using the prysm.bat file on windows with \"set PRYSM_AUTORESTART=true&\", or with docker with \"--restart always\"",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"beacon node\"})/3600",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "(time()-process_start_time_seconds{job=\"validator\"})/3600"
    }
   ]
  },
  {
   "title": "Hardware usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decbytes", "label": "mem usage" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(process_resident_memory_bytes{job=\"$node_job\"}[1m:5s])",
     "legendFormat": "memory {{job}}"
    },
    {
     "expr": "avg_over_time(process_resident_memory_bytes{job=\"$validator_job\"}[1m:5s])",
     "legendFormat": "memory {{job}}"
    },
    {
     "expr": "avg_over_time(process_resident_memory_bytes{job=\"$slasher_job\"}[1m:5s])"
    },
    {
     "expr": "((process_cpu_seconds_total - process_cpu_seconds_total offset 2m) > 0)*100/120/go_maxprocs",
     "legendFormat": "CPU {{job}}"
    }
   ]
  },
  {
   "title": "Balance validators status and participation rate",
   "type": "graph",
   "description": "This graph is made for trading purpose mostly.\nSupposing that if a lot of validators are exiting, price is gonna dump.\n\nAlso this can prevent to exit while exiting queue is too long, same for depositing while pending queue is too long.\n\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "mGNO" }
   ],
   "targets": [
    {
     "expr": "validators_total_balance{state=\"Active\"} / 10e8",
     "legendFormat": "Active"
    },
    {
     "expr": "validators_total_balance{state=\"Pending\"} / 10e8",
     "legendFormat": "Pending"
    },
    {
     "expr": "validators_total_balance{state=\"Exiting\"} / 10e8",
     "legendFormat": "Exiting"
    },
    {
     "expr": "beacon_prev_epoch_target_gwei/beacon_prev_epoch_active_gwei*100",
     "legendFormat": "Participation rate"
    }
   ]
  },
  {
   "title": "Peers connected",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\"}"
    }
   ]
  },
  {
   "title": "Alert: 50 slots behind",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot",
     "legendFormat": "node slots behind"
    }
   ]
  },
  {
   "title": "Alert: Process down",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"beacon node\"}",
     "legendFormat": "beacon node"
    },
    {
     "expr": "up{job=\"validator\"}",
     "legendFormat": "validator"
    }
   ]
  },
  {
   "title": "Slots behind",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot",
     "legendFormat": "Slots behind"
    }
   ]
  },
  {
   "title": "Alert: Hourly earning <= 0",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(validator_balance) - sum(validator_balance offset 1h) - count(validator_balance > 16)*32 + count(validator_balance offset 1h > 0)*32",
     "legendFormat": "validators earning on 1h"
    }
   ]
  },
  {
   "title": "Alert: 50 errors  or 100 warns  in 1h",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(log_entries_total{job=\"beacon node\", level=\"error\"}[1h]) > 0) ",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(delta(log_entries_total{job=\"beacon node\", level=\"warning\"}[1h]) > 0)",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Node process started",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"$node_job\"})/3600"
    }
   ]
  },
  {
   "title": "Alert: Validator has been slashed",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(validator_statuses, \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")",
     "legendFormat": "{{pubkey}}"
    }
   ]
  },
  {
   "title": "Alert: Participation rate < 66%",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 53 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "beacon_prev_epoch_target_gwei/beacon_prev_epoch_active_gwei*100"
    }
   ]
  },
  {
   "title": "Hourly log type counter",
   "type": "bargauge",
   "description": "This panel won't have consistant values during the first hour of the node started process",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(delta(log_entries_total{job=\"$node_job\", level=\"error\"}[1h]) > 0)",
     "legendFormat": "error"
    },
    {
     "expr": "sum(delta(log_entries_total{job=\"$node_job\", level=\"warning\"}[1h]) > 0)",
     "legendFormat": "warning"
    }
   ]
  },
  {
   "title": "ALERTS",
   "type": "stat",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  { "title": "All alerts", "type": "alertlist", "gridPos": { "h": 10, "w": 5, "x": 19, "y": 55 } }
 ]
}