{
 "title": "Router Dashboard",
 "tags": [
  "router",
  "metrics"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "chain", "query": { "query": "label_values(sendingChainId)" } }
  ]
 },
 "panels": [
  { "title": "Quick Overall Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
   "options": {
    "content": "<img width=\"183\" height=\"45\" src=\"https://connext.network/images/connext__Logo--WhiteText-MultiColor-p-500.png\">\n\n<div style=\"margin-top: 30px;\">\n<div style=\"font-weight: 800; font-size: 18px;\">The Interoperability Protocol of L2 Ethereum.</div>\n<div style=\"margin-top:5px;\">Connext is the leading protocol for fast, fully noncustodial transfers and contract calls between EVM-compatible systems.</div>\n<div style=\"margin-top:10px; font-weight: 800; font-size: 18px;\">Helpful Links</div>\n<div style=\"\">\n<ul>\n  <li><a href=\"https://docs.connext.network/\" target=\"_blank\">Docs</a></li>\n  <li><a href=\"https://explorer.connext.network/\" target=\"_blank\">Explorer</a></li>\n  <li><a href=\"https://discord.com/invite/VcNFQdKuxM\" target=\"_blank\">Discord</a></li>\n  <li><a href=\"https://twitter.com/connextnetwork\" target=\"_blank\">Twitter</a></li>\n</ul>\n</div>\n</div>\n"
   }
  },
  {
   "title": "Auction Received",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(router_auction_received[$__range]))"
    }
   ]
  },
  {
   "title": "Attempted Transfers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(router_transfer_attempt[$__range]))"
    }
   ]
  },
  {
   "title": "Fees Collected in USD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(router_fees_usd[$__range]))",
     "legendFormat": "FeesCollected"
    }
   ]
  },
  {
   "title": "Router on Chain Liquidity in USD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(router_onchain_liquidity)" }
   ]
  },
  {
   "title": "Auction Responses",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(router_auction_attempt[$__range]))",
     "legendFormat": "Attempt"
    }
   ]
  },
  {
   "title": "Successful Transfers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(router_transfer_successful[$__range]))"
    }
   ]
  },
  {
   "title": "Costs in USD",
   "type": "stat",
   "description": "Gas costs and relayer fees",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(router_gas_consumed_usd[$__range])) + sum(increase(relayer_fees_paid_usd[$__range]))",
     "legendFormat": "FeesCollected"
    }
   ]
  },
  {
   "title": "Router Transer Volume in USD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(router_transfer_volume[$__range]))",
     "legendFormat": "FeesCollected"
    }
   ]
  },
  {
   "title": "Net Profits in USD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(router_fees_usd[$__range])) - sum(increase(router_gas_consumed_usd[$__range])) - sum(increase(relayer_fees_paid_usd[$__range]))",
     "legendFormat": "LiquidityRemoved"
    }
   ]
  },
  {
   "title": "Liquidity Supplied in USD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(liquidity_supplied_usd)", "legendFormat": "LiquiditySupplied" }
   ]
  },
  {
   "title": "Liquidity Removed in USD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(liquidity_removed_usd)", "legendFormat": "LiquidityRemoved" }
   ]
  },
  {
   "title": "Liquidity Locked in USD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(liquidity_locked_usd)", "legendFormat": "LiquidityLocked" }
   ]
  },
  {
   "title": "Auction By Chain",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (receivingChainId) (increase(router_auction_received[$__range]))"
    },
    {
     "expr": "sum by (receivingChainId) (increase(router_auction_attempt[$__range]))"
    }
   ]
  },
  {
   "title": "Auction Received  Rate By Chain",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (receivingChainId) (rate(router_auction_received[$__range]))",
     "legendFormat": "{{receivingChainId}}"
    }
   ]
  },
  {
   "title": "Auction Attempt  Rate By Chain",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (receivingChainId) (rate(router_auction_attempt[$__range]))",
     "legendFormat": "{{receivingChainId}}"
    }
   ]
  },
  {
   "title": "Transfer By Chain",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (receivingChainId) (increase(router_transfer_successful[$__range]))"
    },
    {
     "expr": "sum by (receivingChainId) (increase(router_transfer_attempt[$__range]))"
    },
    {
     "expr": "(sum by (receivingChainId) (increase(router_transfer_successful[$__range]))) / (sum by (receivingChainId) (increase(router_transfer_attempt[$__range])))"
    }
   ]
  },
  {
   "title": "Transfer Attempt  Rate By ChainId",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (receivingChainId) (rate(router_transfer_attempt[$__range]))",
     "legendFormat": "{{ChainId}}"
    }
   ]
  },
  {
   "title": "Transfer Successful  Rate By ChainId",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (receivingChainId) (rate(router_transfer_successful[$__range]))",
     "legendFormat": "{{ChainId}}"
    }
   ]
  },
  {
   "title": "Router Transfer Volume by Chain",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (chainId) (increase(router_transfer_volume[$__range]))"
    }
   ]
  },
  {
   "title": "Router Chain Balance by Chain",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (chainId) (increase(router_gas_balance[$__range]))"
    }
   ]
  },
  {
   "title": "Transaction States",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "sum by (chainId) (increase(sender_prepared[$__range]))"
    },
    {
     "expr": "sum by (chainId) (increase(receiver_prepared[$__range]))"
    },
    {
     "expr": "sum by (chainId) (increase(sender_cancel[$__range]))"
    },
    {
     "expr": "sum by (chainId) (increase(receiver_cancel[$__range]))"
    },
    {
     "expr": "sum by (chainId) (increase(sender_fulfilled[$__range]))"
    },
    {
     "expr": "sum by (chainId) (increase(receiver_fulfilled[$__range]))"
    },
    {
     "expr": "sum by (chainId) (increase(sender_expired[$__range]))"
    },
    {
     "expr": "sum by (chainId) (increase(receiver_expired[$__range]))"
    },
    {
     "expr": "sum by (chainId) (increase(receiver_failed_prepare[$__range]))"
    },
    {
     "expr": "sum by (chainId) (increase(sender_failed_fulfill[$__range]))"
    },
    {
     "expr": "sum by (chainId) (increase(sender_failed_cancel[$__range]))"
    },
    {
     "expr": "sum by (chainId) (increase(receiver_failed_cancel[$__range]))"
    }
   ]
  },
  {
   "title": "Rpc Node/Subgraph Chain Head By Chain",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 90 },
   "targets": [
    { "expr": "(rpc_head-subgraph_head)" }
   ]
  },
  { "title": "RECEIVING - CHAIN:  $chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 }, "repeat": "chain" },
  {
   "title": "Auction By Asset",
   "type": "table",
   "gridPos": { "h": 16, "w": 19, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (receivingAssetName) (increase(router_auction_received{receivingChainId=\"$chain\"}[$__range]))"
    },
    {
     "expr": "sum by (receivingAssetName) (increase(router_auction_attempt{receivingChainId=\"$chain\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Auction Received Total ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(router_auction_received{receivingChainId=\"$chain\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Auction Attempt  Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 108 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(router_auction_attempt{receivingChainId=\"$chain\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Auction Received  Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (receivingAssetName) (rate(router_auction_received{receivingChainId=\"$chain\"}[$__range]))",
     "legendFormat": "{{receivingAssetName}}"
    },
    {
     "expr": "sum(rate(router_auction_received{receivingChainId=\"$chain\"}[$__range]))",
     "legendFormat": "Total Rate"
    }
   ]
  },
  {
   "title": "Auction Attempt  Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (receivingAssetName) (rate(router_auction_attempt{receivingChainId=\"$chain\"}[$__range]))",
     "legendFormat": "{{receivingAssetName}}"
    },
    {
     "expr": "sum(rate(router_auction_received{receivingChainId=\"$chain\"}[$__range]))",
     "legendFormat": "Total Rate"
    }
   ]
  },
  {
   "title": "Transfer By Asset",
   "type": "table",
   "gridPos": { "h": 16, "w": 19, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (receivingAssetName) (increase(router_transfer_successful{receivingChainId=\"$chain\"}[$__range]))"
    },
    {
     "expr": "sum by (receivingAssetName) (increase(router_transfer_attempt{receivingChainId=\"$chain\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Transfer Successful %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(router_transfer_successful{receivingChainId=\"$chain\"}[$__range])) / sum(increase(router_transfer_attempt{receivingChainId=\"$chain\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Transfer Attempt  Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 142 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(router_transfer_attempt{receivingChainId=\"$chain\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Transfer Successful Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 147 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(router_transfer_successful{receivingChainId=\"$chain\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Transfer Attempt  Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (receivingAssetName) (rate(router_transfer_attempt{receivingChainId=\"$chain\"}[$__range]))",
     "legendFormat": "{{sendingAssetName}}"
    },
    {
     "expr": "sum(rate(router_transfer_attempt{receivingChainId=\"$chain\"}[$__range]))",
     "legendFormat": "Total Rate"
    }
   ]
  },
  {
   "title": "Transfer Successful  Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (receivingAssetName) (rate(router_transfer_successful{receivingChainId=\"$chain\"}[$__range]))",
     "legendFormat": "{{receivingAssetName}}"
    },
    {
     "expr": "sum(rate(router_transfer_successful{receivingChainId=\"$chain\"}[$__range]))",
     "legendFormat": "Total Rate"
    }
   ]
  },
  {
   "title": "Router Fees by Asset",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "increase(router_fees_usd{chainId=\"$chain\"}[$__range])"
    }
   ]
  },
  {
   "title": "Router Fees Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(router_fees_usd{chainId=\"$chain\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Router Transfer Volume by Asset",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "increase(router_transfer_volume{chainId=\"$chain\"}[$__range])"
    }
   ]
  },
  {
   "title": "Router Transfer Volume Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(router_transfer_volume{chainId=\"$chain\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Gas Consumed by Reason",
   "type": "table",
   "gridPos": { "h": 16, "w": 17, "x": 0, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "increase(router_gas_consumed_usd{chainId=\"$chain\"}[$__range])"
    }
   ]
  },
  {
   "title": "Router Chain Balance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "router_gas_balance{chainId=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Gas Consumed Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(router_gas_consumed_usd{chainId=\"$chain\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Rpc Node/Subgraph Chain Head",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 204 },
   "targets": [
    {
     "expr": "rpc_head{chainId=\"$chain\"}",
     "legendFormat": "RPC"
    },
    {
     "expr": "subgraph_head{chainId=\"$chain\"}",
     "legendFormat": "Subgraph"
    }
   ]
  },
  {
   "title": "Rpc Chain Head - Subgraph Chain Head",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_head{chainId=\"$chain\"} - subgraph_head{chainId=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Transaction States",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 212 },
   "targets": [
    {
     "expr": "sum by (assetName) (increase(sender_prepared{chainId=\"$chain\"}[$__range]))"
    },
    {
     "expr": "sum by (assetName) (increase(receiver_prepared{chainId=\"$chain\"}[$__range]))"
    },
    {
     "expr": "sum by (assetName) (increase(sender_cancel{chainId=\"$chain\"}[$__range]))"
    },
    {
     "expr": "sum by (assetName) (increase(receiver_cancel{chainId=\"$chain\"}[$__range]))"
    },
    {
     "expr": "sum by (assetName) (increase(sender_fulfilled{chainId=\"$chain\"}[$__range]))"
    },
    {
     "expr": "sum by (assetName) (increase(receiver_fulfilled{chainId=\"$chain\"}[$__range]))"
    },
    {
     "expr": "sum by (assetName) (increase(sender_expired{chainId=\"$chain\"}[$__range]))"
    },
    {
     "expr": "sum by (assetName) (increase(receiver_expired{chainId=\"$chain\"}[$__range]))"
    },
    {
     "expr": "sum by (assetName) (increase(receiver_failed_prepare{chainId=\"$chain\"}[$__range]))"
    },
    {
     "expr": "sum by (assetName) (increase(sender_failed_fulfill{chainId=\"$chain\"}[$__range]))"
    },
    {
     "expr": "sum by (assetName) (increase(sender_failed_cancel{chainId=\"$chain\"}[$__range]))"
    },
    {
     "expr": "sum by (assetName) (increase(receiver_failed_cancel{chainId=\"$chain\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Transaction States Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 222 },
   "targets": [
    {
     "expr": "sum(rate(sender_prepared{chainId=\"$chain\"}[$__range]))",
     "legendFormat": "SenderPrepared"
    },
    {
     "expr": "sum(rate(receiver_prepared{chainId=\"$chain\"}[$__range]))",
     "legendFormat": "ReceiverPrepared"
    },
    {
     "expr": "sum(rate(sender_cancel{chainId=\"$chain\"}[$__range]))",
     "legendFormat": "SenderCancel"
    },
    {
     "expr": "sum(rate(receiver_cancel{chainId=\"$chain\"}[$__range]))",
     "legendFormat": "ReceiverCancel"
    },
    {
     "expr": "sum(rate(sender_fulfilled{chainId=\"$chain\"}[$__range]))",
     "legendFormat": "SenderFulfilled"
    },
    {
     "expr": "sum(rate(receiver_fulfilled{chainId=\"$chain\"}[$__range]))",
     "legendFormat": "ReceiverFulfilled"
    },
    {
     "expr": "sum(rate(sender_expired{chainId=\"$chain\"}[$__range]))",
     "legendFormat": "SenderExpired"
    },
    {
     "expr": "sum(rate(receiver_expired{chainId=\"$chain\"}[$__range]))",
     "legendFormat": "ReceiverExpired"
    },
    {
     "expr": "sum(rate(receiver_failed_prepare{chainId=\"$chain\"}[$__range]))",
     "legendFormat": "ReceiverFailedPrepare"
    },
    {
     "expr": "sum(rate(sender_failed_fulfill{chainId=\"$chain\"}[$__range]))",
     "legendFormat": "SenderFailedFulFill"
    },
    {
     "expr": "sum(rate(sender_failed_cancel{chainId=\"$chain\"}[$__range]))",
     "legendFormat": "SenderFailedCancel"
    },
    {
     "expr": "sum(rate(receiver_failed_cancel{chainId=\"$chain\"}[$__range]))",
     "legendFormat": "ReceiverFailedCancel"
    }
   ]
  }
 ]
}